name: notebooks
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - ipykernel
  - tqdm
  - pandas
  - matplotlib
  - xarray
  - dask
  - intake-esm
  - seaborn
  - fsspec
  - dask-jobqueue
  - ipywidgets
  - jupyter
  - cartopy
  - h5py
  - geoviews
  - py-cordex
