name: cmip-processing
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3
  - ipykernel
  - tqdm
  - pandas
  - matplotlib
  - xarray
  - dask
  - intake-esm
  - seaborn
  - fsspec
  - dask-jobqueue
  - ipywidgets
  - jupyter
  - holoviews
  - hvplot
  - cartopy
  - h5py
  - geoviews
